#!/usr/bin/env perl
#
# Reads a list of usernames from stdin, and prints the username if the user has
# a mailbox.

use strict;
use Cyrus::IMAP::Admin;

my $admin = "cyrus";
my $admin_pass = "foo";

my $client = Cyrus::IMAP::Admin->new("localhost");

$client->authenticate('login', 'imap', '', $admin, '0', '10000', $admin_pass);

(print $client->{error} && return(1)) if $client->{error};

while (<>) {
    chop $_;
    $client->listmailbox("user.$_") && print "$_\n";
}
