#!/bin/sh
#
# Script which reads a file called 'new_users', generates a random password,
# sets the LDAP password for that user, and writes it to passwords.txt.

ADMIN_DN='cn=admin,dc=example,dc=com'
BASE_DN='ou=People,dc=example,dc=com'
PASSFILE='passwords.txt'

read -s -p "Enter the LDAP admin password: " ADMINPASS
echo

cat new_users | \
  while read USER
  do
    USERPASS=$(pwgen -c -n -1)
    ldappasswd -x -Z -w $ADMINPASS \
      -D "$ADMIN_DN" -s "$USERPASS" "uid=$USER,$BASE_DN"
    echo "$USER: $USERPASS" >> $PASSFILE
  done
