#!/bin/sh
#
# For: Postfix + Amavis
#
# Returns all spam scores from the mail log.  Use the R script spamscore.r to
# create a histogram for the spam scores.

echo hits
(zgrep ', Hits: ' /var/log/mail.log.*.gz; grep ', Hits: ' /var/log/mail.log{,.0}) | \
	sed -r 's/.*, Hits: ([^,]+),.*/\1/' | \
	grep -v '^-$' | \
	grep -E '^-?[0-9]+\.[0-9]+$'
